      SUBROUTINE XERBLA(SRNAME, INFO)
C
CF2PY INTENT(CALLBACK, HIDE) PYTHON_CALLBACK
C
      CHARACTER*(*) SRNAME
      INTEGER INFO
C
      EXTERNAL PYTHON_CALLBACK
C
      CALL PYTHON_CALLBACK(SRNAME, INFO)
C
      RETURN
C
      END
